---
title: "TidyTuesday - week 23"
author: "Maja Urankar"
date: "2026-05-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggrepel)
library(lubridate)
```

```{r}
game_films <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2026/2026-06-09/game_films.csv')
```

```{r}
game_films %>% 
  ggplot(aes(x = rotten_tomatoes, y = metacritic)) + 
  geom_point(alpha = 0.3) +
  geom_point(data = ~ filter(.x, title == "Final Fantasy VII: Advent Children"),
    color = "black", size = 2) +
  geom_text_repel(data = game_films %>% filter(title == "Final Fantasy VII: Advent Children"), aes(label = title)) +
  expand_limits(y = 0) + 
  theme_minimal() + 
  labs(x = "Rotten Tomatoes critic score", y = "Metacritic score", title = "XXXXX", caption = "XXXXX")

# NOTE: only theatrical releases have this
```

```{r}
game_films %>% 
  ggplot(aes(x = rotten_tomatoes, col = category)) + 
  geom_density() + 
  theme_minimal()
```

```{r}
game_films %>% 
  filter(release_date <= "2025-12-31") %>% 
  mutate(year = year(release_date)) %>% 
  group_by(category, year) %>% 
  count() %>% 
  ggplot(aes(x = year, y = n, fill = category)) + 
  geom_col() + 
  facet_wrap(~category) + 
  theme_minimal()
```


```{r}
game_films %>% 
  group_by(director) %>% 
  count() %>% 
  arrange(desc(n))


game_films %>% 
  filter(str_detect(director, "Kunihiko Yuyama"))
```

```{r}
game_films %>% 
  mutate(year = year(release_date)) %>% 
  ggplot(aes(x = year, y = metacritic)) + 
  geom_point() + 
  expand_limits(y = 0)

game_films %>% 
  mutate(year = year(release_date)) %>% 
  ggplot(aes(x = year, y = rotten_tomatoes)) + 
  geom_point() + 
  expand_limits(y = 0)

game_films %>% 
  group_by(original_game_publisher) %>% 
  count()
```






